version: '3.9'
services:
  mariadb:
    container_name: mariadb10
    image: mariadb:10.1.10
    ports:
      - '3333:3333'
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: serverless
      MYSQL_ROOT_PASSWORD: Password123#
    restart: always
  mssql:
    container_name: azure-sql-edge
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - '1444:1444'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password123#
      MSSQL_PID: Developer
    restart: always
