version: '3.9'
services:
  mariadb:
    container_name: mysql-mariadb
    image: mariadb:10.1.10
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: always
  mssql:
    container_name: mssql-azure
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - '1444:1433'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: Developer
    restart: always
