version: '3.9'
services:
  mariadb:
    container_name: mysql-mariadb
    image: mariadb:10.1.10
    ports:
      - '3303:3303'
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: serverless
      MYSQL_ROOT_PASSWORD: password123
    restart: always
  mssql:
    container_name: mssql-azure
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - '1444:1444'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password123#
      MSSQL_PID: Developer
    restart: always
